name: route_hierarchical
version: 0.6.2
authors:
- Justin Fagnani <justinfagnani@google.com>
- Pavel Jbanov <pavelj@google.com>
description: A client routing library for Dart
homepage: https://github.com/angular/route.dart
dependencies:
  logging: any
dev_dependencies:
  browser: any
  mockito: any
  test: any
